Repository BaloneyBoy97/PSD-TEAM, pull requests merged in 2024-06, with the labels that each got.

#19 Zan flights
  airView/database/appdata.db
  airView/database/data.py
Labels: Code

#20 Zan flights
  airView/authentication/feature.py
Labels: bug

#23 Modified Database.
  airView/database/appdata.db
  airView/database/data.py
  airView/environment/app.py
Labels: Code

#24 create new attribute is_checkedin in bookings table
  airView/database/appdata.db
  airView/database/data.py
Labels: Code

#27 Booking: Createst Unit Tests and DB Modification
  airView/booking/__init__.py
  airView/booking/feature.py
  airView/booking/operation.py
  airView/booking/unittest_booking.py
  airView/database/appdata.db
  airView/database/data.py
  airView/environment/app.py
  airView/flightSearch/feature.py
Labels: Code

#29 Modification: Booking Module and unittest_booking.py. Update: back end files with uniformed comment format
  airView/app.log
  airView/authentication/__pycache__/__init__.cpython-311.pyc
  airView/authentication/__pycache__/feature.cpython-311.pyc
  airView/authentication/__pycache__/operation.cpython-311.pyc
  airView/authentication/feature.py
  airView/authentication/operation.py
  airView/booking/__pycache__/__init__.cpython-311.pyc
  airView/booking/__pycache__/feature.cpython-311.pyc
  airView/booking/__pycache__/operation.cpython-311.pyc
  airView/booking/__pycache__/unittest_booking.cpython-311.pyc
  airView/booking/feature.py
  airView/booking/operation.py
  airView/booking/unittest_booking.py
  airView/database/appdata.db
  airView/environment/__pycache__/__init__.cpython-311.pyc
  airView/environment/__pycache__/app.cpython-311.pyc
  airView/environment/app.py
Labels: bug, documentation, enhancement, Code

#33 email notification integration test
  airView/.env
  airView/app.log
  airView/booking/__pycache__/feature.cpython-311.pyc
  airView/booking/__pycache__/operation.cpython-311.pyc
  airView/environment/__pycache__/app.cpython-311.pyc
  airView/tests/__pycache__/integration_test_email.cpython-311.pyc
  airView/tests/__pycache__/integratoin_test_booking_email.cpython-311.pyc
  airView/tests/__pycache__/unittest_booking.cpython-311.pyc
  airView/tests/integration_test_email.py
  airView/tests/integratoin_test_booking_email.py
  airView/tests/sent_test_email.py
Labels: bug, documentation, enhancement, Code

#35 file name correction
  airView/tests/__pycache__/integration_test_booking_email.cpython-311.pyc
  airView/tests/__pycache__/unittest_auth.cpython-311.pyc
  airView/tests/integration_test_booking_email.py
Labels: bug, documentation

#48 intergeration testcases for Flight search
  airView/app.log
  airView/authentication/__pycache__/operation.cpython-39.pyc
  airView/authentication/operation.py
  airView/booking/__pycache__/feature.cpython-39.pyc
  airView/booking/__pycache__/operation.cpython-39.pyc
  airView/flightsearch/operation.py
  airView/templates/home.html
  airView/tests/flightsearch_integerationTest.py
Labels: enhancement, Code, testcases
